/***************************************************************************
 * name: Conner Herriges
 * course: CS 4328 - Operating Systems
 * project: Project1, part1a
 *      This program generates the Fibonacci sequence using Pthreads
 * status: complete
 * compile with gcc -g -Wall -lpthread fibonacci.c -o fibonacci
 **************************************************************************/
 #include<pthread.h>
 #include<stdio.h>
 #include<stdlib.h>

 int sequence[];   /* array to be shared by threads */
 void *fibonacci(void *param);  /* the thread */

 int main()
 {
     int generate;   /* number of Fibonacci numbers the program is to produce */
     int index;
     pthread_t tid;          /* the thread identifier */
     pthread_attr_t attr;    /* set of attributes for the thread */

     printf("Enter the number of Fibonacci numbers to generate: ");
     scanf("%d", &generate);

     pthread_attr_init(&attr); /* get the default attributes */

     /* create the thread */
     pthread_create(&tid, &attr, fibonacci, (void *) generate);

     /* wait for thread to exit */
     pthread_join(tid, NULL);

     /* parent thread prints the sequence generated by child thread */
     printf("The Fibonacci sequence for %d digits is:\n", generate);
     for(index = 0; index < generate; index++){
         printf("%d ", sequence[index]);
     }
     printf("\n");

     return 0;
 }

 void *fibonacci(void *param){
     int fib1 = 0, fib2 = 1;    /* fib1 = (n-2), fib2 = (n-1) */
     int count, num;

     for (count = 0; count < atoi(param); count++) {
         if (count <= 1)
             num = count;
         else {
             num = fib1 + fib2;
             fib1 = fib2;
             fib2 = num;
         }
         sequence[count] = num;
     }
     pthread_exit(0);
 }
